#!/usr/bin/env python3
"""Regenerate js/config-bundle.js and JS bundles after editing config/*.json or source modules."""
import json, re, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)

CONFIG_NAMES = [
  'framework', 'difficulty', 'resources', 'generators', 'upgrades',
  'items', 'artifacts', 'characters', 'achievements', 'events',
  'drops', 'ascension', 'prestige'
]

config = {}
for name in CONFIG_NAMES:
    with open(f'config/{name}.json') as f:
        config[name] = json.load(f)

with open('js/config-bundle.js', 'w') as out:
    out.write('// Generated by scripts/bundle-for-file-protocol.py\n')
    out.write('window.AFK_CONFIG = ')
    json.dump(config, out, indent=2)
    out.write(';\n')

ENGINE_FILES = [
  'js/core/EventBus.js', 'js/game/FormulaEngine.js', 'js/core/ConfigManager.js',
  'js/core/SaveManager.js', 'js/core/ProgressTracker.js', 'js/game/ModifierSystem.js',
  'js/game/GameState.js', 'js/game/systems/GeneratorSystem.js',
  'js/game/systems/PrestigeSystem.js', 'js/game/systems/AscensionSystem.js',
  'js/game/systems/DropSystem.js', 'js/game/systems/AchievementSystem.js',
  'js/game/systems/EventSystem.js', 'js/game/GameLoop.js',
]

def strip_module_syntax(content):
    lines = content.split('\n')
    out_lines = []
    for line in lines:
        if re.match(r"^import\s+", line):
            continue
        for prefix in ('export const', 'export class', 'export function', 'export async function'):
            if line.startswith(prefix):
                line = line.replace('export ', '', 1)
                break
        if line.startswith('export {'):
            continue
        if line.startswith('export default'):
            line = line.replace('export default', 'AFK.', 1)
        out_lines.append(line)
    return '\n'.join(out_lines)

parts = ['// Generated engine bundle for file:// support\n(function () {\nwindow.AFK = window.AFK || {};\nconst AFK = window.AFK;\n']
for fp in ENGINE_FILES:
    with open(fp) as f:
        parts.append(f'\n// --- {fp} ---\n')
        parts.append(strip_module_syntax(f.read()))

bundle = ''.join(parts)
old = '''async function loadAllConfigs() {
  const entries = await Promise.all('''
new = '''async function loadAllConfigs() {
  if (window.AFK_CONFIG) {
    config = window.AFK_CONFIG;
    validateConfig();
    return config;
  }
  const entries = await Promise.all('''
if old in bundle:
    bundle = bundle.replace(old, new)

for name in ['EventBus', 'EVENTS', 'ConfigManager', 'loadAllConfigs', 'validateGeneratorChain', 'SaveManager', 'ProgressTracker',
             'FormulaEngine', 'ModifierSystem', 'GameState', 'createInitialState',
             'GeneratorSystem', 'PrestigeSystem', 'AscensionSystem', 'DropSystem',
             'AchievementSystem', 'EventSystem', 'GameLoop']:
    bundle += f'if (typeof {name} !== "undefined") AFK.{name} = {name};\n'

bundle += '\n}).call(typeof window !== "undefined" ? window : globalThis);\n'

with open('js/afk-engine.bundle.js', 'w') as out:
    out.write(bundle)

UI_FILES = [
  'js/ui/components/Toast.vue.js', 'js/ui/components/Tooltip.vue.js',
  'js/ui/components/EventBanner.vue.js',
  'js/ui/components/ProgressBar.vue.js',
  'js/ui/components/ResourceProgressList.vue.js',
  'js/ui/components/UnlockRequirementsList.vue.js',
  'js/ui/components/MoreInfoButton.vue.js',
  'js/ui/components/EquipmentGrid.vue.js',
  'js/ui/components/UnlockModal.vue.js',
  'js/ui/components/InfoModal.vue.js',
  'js/ui/components/TapButton.vue.js', 'js/ui/components/SkillSlot.vue.js',
  'js/ui/components/BoostSlot.vue.js', 'js/ui/components/PurchaseMultiplier.vue.js',
  'js/ui/ResourceBar.vue.js', 'js/ui/GeneratorPanel.vue.js', 'js/ui/UpgradePanel.vue.js',
  'js/ui/CharacterPanel.vue.js', 'js/ui/InventoryPanel.vue.js', 'js/ui/ArtifactPanel.vue.js',
  'js/ui/AchievementPanel.vue.js',
  'js/ui/AscensionPanel.vue.js', 'js/ui/SettingsPanel.vue.js', 'js/ui/StatsPanel.vue.js',
  'js/ui/ProgressPanel.vue.js', 'js/ui/ActionBar.vue.js', 'js/ui/App.vue.js',
]

def validate_chain(cfg):
    errors = []
    gens = cfg['generators']['generators']
    primary = next((r['codeName'] for r in cfg['resources']['resources'] if r.get('isPrimary')), None)
    for i in range(len(gens) - 1):
        current = gens[i]
        nxt = gens[i + 1]
        produces = [p['resource'] for p in current.get('produces', [])]
        next_costs = [c['resource'] for c in nxt.get('costResources', [])]
        conds = nxt.get('unlockConditions') or {}
        next_held = [c['resource'] for c in (conds.get('conditions') or []) if c.get('type') == 'resourceHeld']
        needed = list(dict.fromkeys(next_costs + next_held))
        for res in needed:
            if res == primary:
                continue
            if res not in produces:
                errors.append(f"{current['codeName']} does not produce {res} for {nxt['codeName']}")
    return errors

UI_IMPORTS = {
  './components/PurchaseMultiplier.vue.js', './components/TapButton.vue.js',
  './components/SkillSlot.vue.js', './components/BoostSlot.vue.js', './components/Toast.vue.js',
  './components/UnlockRequirementsList.vue.js', './components/ProgressBar.vue.js',
  './components/ResourceProgressList.vue.js', './components/MoreInfoButton.vue.js',
  './components/EquipmentGrid.vue.js', './components/UnlockModal.vue.js',
  './components/InfoModal.vue.js',
  './ResourceBar.vue.js', './GeneratorPanel.vue.js', './UpgradePanel.vue.js',
  './CharacterPanel.vue.js', './InventoryPanel.vue.js', './AchievementPanel.vue.js',
  './AscensionPanel.vue.js', './SettingsPanel.vue.js', './StatsPanel.vue.js',
  './ProgressPanel.vue.js', './ActionBar.vue.js', './App.vue.js',
}

def strip_ui(content, declared_imports):
    lines = content.split('\n')
    out, i = [], 0
    while i < len(lines):
        line = lines[i]
        m = re.match(r"^import\s+(\w+)\s+from\s+['\"]([^'\"]+)['\"];?\s*$", line)
        if m:
            name = m.group(1)
            if name not in declared_imports:
                out.append(f'const {name} = AFK_UI.{name};')
                declared_imports.add(name)
            i += 1
            continue
        if re.match(r"^import\s+\{", line):
            i += 1
            continue
        if line.startswith('export default'):
            comp = 'Component'
            for j in range(i + 1, min(i + 5, len(lines))):
                nm = re.search(r"name:\s*'(\w+)'", lines[j])
                if nm:
                    comp = nm.group(1)
                    break
            out.append(f'AFK_UI.{comp} = {{')
            i += 1
            continue
        out.append(line)
        i += 1
    return '\n'.join(out)

ui_parts = ['// Generated UI bundle for file:// support\n(function () {\nwindow.AFK_UI = window.AFK_UI || {};\nconst AFK_UI = window.AFK_UI;\n']
declared_ui_imports = set()
for fp in UI_FILES:
    with open(fp) as f:
        ui_parts.append(f'\n// --- {fp} ---\n')
        ui_parts.append(strip_ui(f.read(), declared_ui_imports))

with open('js/afk-ui.bundle.js', 'w') as out:
    out.write(''.join(ui_parts))
    out.write('\n}).call(typeof window !== "undefined" ? window : globalThis);\n')

print('Regenerated config-bundle.js, afk-engine.bundle.js, afk-ui.bundle.js')

chain_errors = validate_chain(config)
if chain_errors:
    print('Generator chain validation FAILED:')
    for err in chain_errors:
        print(' ', err)
    raise SystemExit(1)
print('Generator chain validation: OK')
